INSERT MeatButType VALUES(UUID_TO_BIN(UUID()), "肉まん", 100, CAST("5000" AS TIME), "とても肉汁がすばらしくジューシーで，食べ応えのある素晴らしい肉まん!", NULL, NULL, CAST(NOW() AS DATETIME), CAST(NOW() AS DATETIME));
INSERT MeatButType VALUES(UUID_TO_BIN(UUID()), "抹茶まん", 140, CAST("5000" AS TIME), "甘々ベーキング", NULL, NULL, CAST(NOW() AS DATETIME), CAST(NOW() AS DATETIME));
INSERT MeatButType VALUES(UUID_TO_BIN(UUID()), "ピザまん", 120, CAST("5000" AS TIME), "人気", NULL, NULL, CAST(NOW() AS DATETIME), CAST(NOW() AS DATETIME));
INSERT MeatButType VALUES(UUID_TO_BIN(UUID()), "あんまん", 100, CAST("5000" AS TIME), "元気100倍", NULL, NULL, CAST(NOW() AS DATETIME), CAST(NOW() AS DATETIME));
INSERT MeatButType VALUES(UUID_TO_BIN(UUID()), "黒豚まん", 200, CAST("5000" AS TIME), "高いよ", NULL, NULL, CAST(NOW() AS DATETIME), CAST(NOW() AS DATETIME));
INSERT MeatButType VALUES(UUID_TO_BIN(UUID()), "テストまん", 200, CAST("0100" AS TIME), "1分で出来ます", NULL, NULL, CAST(NOW() AS DATETIME), CAST(NOW() AS DATETIME));
SELECT BIN_TO_UUID(ID) AS ID, Name, Price, Time, Description, ImageSrc, Priority, CreateTime, UpdateTime FROM MeatButType ORDER BY Priority DESC;